name: Deploy to GitHub Pages on master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # Step 3: Install NPM dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build project
        run: npm run build

      # Step 5: Clean existing files in the root directory to avoid conflicts
      - name: Clean existing files
        run: |
          find . -maxdepth 1 ! -name '.git' -exec rm -rf {} +

      # Step 6: Move Built Files to Root of the Repo for GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          cp -r dist/* .
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}